name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 1 * *' # 매월 1일 자정
  workflow_dispatch: # 수동 실행

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Empty Commit
        run: |
          git config --global user.name "yammyom"
          git config --global user.email "yam304258@gmail.com"
          
          git commit --allow-empty -m "chore: keepalive commit to prevent workflow suspension"
          git push origin HEAD